### ISSUE TITLE
Improve NumberOfMarksCost class

### ISSUE THREAD

**Issue by carmocca** [CloudCoders/Algorithms#25]
Make it so it uses random marks to be beaten and arrays, which have to be the same for each implementation and make it so it averages the time of X iterations.

**Comment by tonilopezmr** [comment]
@carmocca have a look this and comment what do you think.

**Comment by tonilopezmr** [comment]
@josegarm  I have reverted your changes  in #27 to put two different solutions inside the repo and discuss the different ways to implement `NumberOfMarksCost``

Branch to @josegarm solution: enhancement/josegarm/markscost
Branch to @carmocca solution: enhancement/carmocca/markscost

You should create a PR in those branches.

@josegarm you MUST create a PR to only for resolve the problem with your JoseMImp, Do you understand me?

Les't go!

**Comment by tonilopezmr** [comment]
@carmocca Have a look 2ea73a3 and if you agree with @josegarm I'm going to merge `enhancement/josegarm/markcost` solution.

**Comment by tonilopezmr** [comment]
@josegarm create a PR to las commits that @carmocca have said!

**Comment by tonilopezmr** [comment]
@carmocca You can see the final result!!! weeee!!


![](http://i.imgur.com/ho1aO.gif)
