### ISSUE TITLE
Add Graphs 

### ISSUE THREAD

**Issue by JoseLlorensRipolles** [CloudCoders/Algorithms#38]
Add Graph abstract class, Adjacent class and DirectedGraph(implementation).

**Comment by tonilopezmr** [comment]
@JoseLlorensRipolles Check out this #39 and #40

**Comment by tonilopezmr** [comment]
Hey @JoseLlorensRipolles luck this [commit](https://github.com/tonilopezmr/Algorithms/commit/0af2197b5d1d53248ca1a641fd0090c368f89a49)

And give me your opinion
